org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

neogradle.subsystems.parchment.minecraftVersion=1.21
neogradle.subsystems.parchment.mappingsVersion=2024.07.28

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.4
neo_version_range=[21.0.102-beta,)
loader_version_range=[4,)

#Mod
mod_id=ends_delight
mod_name=End's Delight
mod_license=MIT License
mod_version=2.5
mod_group_id=cn.foggyhillside.ends_delight
mod_credits=GamingeckeSpace, Lobster0228, mpustovoi, PExPE3, Roby1164, SABITRON, tankplanelaserkoala, TheLegendofSaram, unroman and many others!
mod_authors=FoggyHillside
mod_description=An addon mod for Farmer's Delight based around adding culinary content to the End!

#Dependencies
farmersdelight_version=8007613
farmersdelight_version_range=[1.3.1,)
