
modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"
[[mods]]
modId="ends_delight"
version="1.18.2-1.1"
displayName="End's Delight"
logoFile="logo.png"
logoBlur=false
authors="FoggyHillside"
description='''
This mod adds some food and drink about the End
'''
[[dependencies.ends_delight]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ends_delight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ends_delight]]
    modId="farmersdelight"
    mandatory=true
    versionRange="[1.18.2-1.2.0,)"
    ordering="AFTER"
    side="BOTH"
