
modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"
[[mods]]
modId="ends_delight"
version="1.18.2-1.2.1"
displayName="End's Delight"
logoFile="logo.png"
logoBlur=false
credits="FoggyHillside, PExPE3, unroman"
authors="FoggyHillside"
description='''
An addon mod for Farmer's Delight based around adding culinary content to the end!
'''
[[dependencies.ends_delight]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ends_delight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ends_delight]]
    modId="farmersdelight"
    mandatory=true
    versionRange="[1.18.2-1.2.1,)"
    ordering="AFTER"
    side="BOTH"
