modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"
[[mods]]
modId="ends_delight"
version="1.16.5-1.8"
displayName="End's Delight"
logoFile="logo.png"
logoBlur=false
credits="FoggyHillside, PExPE3, SKZGx"
authors="FoggyHillside"
description='''
An addon mod for Farmer's Delight based around adding culinary content to the end!
'''
[[dependencies.ends_delight]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ends_delight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ends_delight]]
    modId="farmersdelight"
    mandatory=true
    versionRange="[1.16.5-0.6.0,)"
    ordering="AFTER"
    side="BOTH"

